steps:

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$_GCP_PROJECT/mlflow-server:$_SERVER', '.']


  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_GCP_PROJECT/mlflow-server:$_SERVER']
  
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', $_SERVER_ENDPOINT, '--image', 'gcr.io/$_GCP_PROJECT/mlflow-server:$_SERVER', '--region', 'us-central1-a']

images:
  - gcr.io/$_GCP_PROJECT/mlflow-server:$_SERVER
